import type { BingoTemplate } from './types';

export const BINGO_TEMPLATES: BingoTemplate[] = [
  {
    id: 'meeting',
    name: 'Meeting Bingo',
    description: 'Klassische Phrasen aus dem täglichen Meeting-Wahnsinn',
    words: [
      'Kurze Frage',
      'Am Ende des Tages',
      'Quick Sync',
      'Alignment',
      'Moving forward',
      'Low-hanging fruit',
      'Auf den gleichen Stand bringen',
      'Bandwidth',
      'Deep Dive',
      'Takeaways',
      'Das ist eigentlich ganz einfach',
      'Können wir das offline klären?',
      'Wer führt das Protokoll?',
      'Ich bin gerade auf Mute',
      'Könnt ihr mich hören?',
      'Synergien',
      'Paradigmenwechsel',
      'Ganzheitlicher Ansatz',
      'Proaktiv',
      'Transparenz',
      'Best Practice',
      'Auf Kurs bleiben',
      'Touchpoint',
      'Roadmap',
      'Pain Points',
      'Win-Win',
      'Gamechanger',
      'Disruptiv',
    ],
  },
  {
    id: 'office',
    name: 'Büro Bingo',
    description: 'Typische Bürosituationen und Phrasen',
    words: [
      'Der Drucker streikt',
      'Kühlschrank ist leer',
      'Jemand stiehlt mein Mittagessen',
      'Meeting zu lang',
      'Kein Kaffee mehr',
      'Internet weg',
      'Passwort vergessen',
      '"Kurz mal stören"',
      'Klimaanlage zu kalt',
      'Klimaanlage zu warm',
      'Aufzug kaputt',
      'Parkplatzstreit',
      'Geburtstagskuchen',
      'Freitagsnachmittag E-Mail',
      'Last-Minute-Änderungen',
      'Falscher Reply All',
      'Stundenlange Präsentation',
      'Niemand hört zu',
      'Chef fragt nach Status',
      '"Das haben wir immer so gemacht"',
      'Handy klingelt im Meeting',
      'Jemand hustet ohne Maske',
      'Schreibtisch-Chaos',
      'Kabelsalat',
      'Feierabend-Anfrage',
    ],
  },
  {
    id: 'developer',
    name: 'Developer Bingo',
    description: 'Das tägliche Leben als Software-Entwickler',
    words: [
      '"Works on my machine"',
      'Undefined is not a function',
      'Stack Overflow copy/paste',
      'Git merge conflict',
      '"Quick fix"',
      'Legacy code',
      'TODO: später fixen',
      'Deployment am Freitag',
      'Keine Tests geschrieben',
      '"Das war so vorher schon"',
      'Requirements ändern sich',
      'Infinite loop',
      'README fehlt',
      'Keine Dokumentation',
      'Ungetestetes Prod-Deployment',
      '10x Entwickler',
      'Rewrite from scratch',
      'Bikeshedding',
      'Over-engineering',
      '"Ist doch klar"',
      'NullPointerException',
      'Off-by-one error',
      'Race condition',
      'Deadlock',
      'Cache invalidation',
      '404 Not Found',
      'It depends',
      'Have you tried turning it off?',
    ],
  },
  {
    id: 'custom',
    name: 'Eigenes Bingo',
    description: 'Erstelle dein eigenes Bingo mit eigenen Wörtern',
    words: [],
  },
];

export function getTemplate(id: string): BingoTemplate | undefined {
  return BINGO_TEMPLATES.find((t) => t.id === id);
}
